FROM runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies including rclone and fuse
RUN apt-get update -qq &&     apt-get install -y -qq git ffmpeg curl dos2unix fuse unzip wget openssh-server &&     curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip &&     unzip -q rclone-current-linux-amd64.zip &&     cp rclone-*-linux-amd64/rclone /usr/bin/ &&     chmod 755 /usr/bin/rclone &&     rm -rf rclone-* &&     rm -rf /var/lib/apt/lists/*

